# Generated by Django 4.2.16 on 2025-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('instagra', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Logo')),
                ('is_ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
