# Generated by Django 5.1.2 on 2025-01-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descrição', models.TextField()),
                ('fotoprojeto', models.ImageField(blank=True, null=True, upload_to='projeto', verbose_name='Logo')),
                ('is_ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='conselho',
            options={'ordering': ['id'], 'verbose_name': 'Conselho', 'verbose_name_plural': 'Conselheiros'},
        ),
        migrations.AlterField(
            model_name='conselho',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='conselho', verbose_name='Logo'),
        ),
    ]
