# Generated by Django 4.2.16 on 2025-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_descrição_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fotoprojeto',
            field=models.FileField(blank=True, null=True, upload_to='projeto', verbose_name='fotoprojeto'),
        ),
    ]
