# Generated by Django 4.2.16 on 2025-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_projeto_fotoprojeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conselho',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='conselho', verbose_name='Foto'),
        ),
    ]
