# Generated by Django 4.2.16 on 2025-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_conselho_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
