# Generated by Django 4.2.16 on 2025-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_projeto_is_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrocel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discricao', models.CharField(max_length=100)),
                ('fotocarrocel', models.FileField(blank=True, null=True, upload_to='carrocel', verbose_name='fotocarrocel')),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='is_principal',
        ),
    ]
