# Generated by Django 4.2.16 on 2025-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_carousel_delete_carrocel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
